### PR TITLE
Dockerfile: remove superfluous ARG line

### PR DESCRIPTION
**Pull request by mbeijen**

### CODE REVIEW

**Review by fish98 — APPROVED** [review]
LGTM. The args is not used.

**Comment by iosifache** [comment]
We spotted this during the workshop. Thanks for the PR (and the implicit reminder 😆)!

**Review by iosifache — APPROVED** [review]

**Comment by mbeijen** [comment]
> We spotted this during the workshop. Thanks for the PR (and the implicit reminder 😆)!

Exactly! I was in the workshop, and that was when I made the PR. We had the brief chat about python being tested but Perl not :-)

thanks for the workshop, I enjoyed it, even though of course you can never get much done in a workshop setting it was insightful

**Comment by iosifache** [comment]
Yeah, the "_We spotted this during the workshop_" mention was exactly because of that! Hopefully, someone will see your comment and will start allocating some time for fuzzing the Perl interpreter 👀

I'm soooo happy that you liked it! You surely have implicit limitation during a workshop (different operating systems, different architectures, random errors, limited time, etc.), but I hope all the people left the room with the belief that the people working of fuzzing infrastructure (CC: @DonggeLiu and the OSS-Fuzz crew ;) did an awesome job on lowering the barrier to entry for continuous fuzz testing for OSS projects.

**Pull request merged**
